# Generated by Django 5.2 on 2025-04-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Admin'), ('usuario', 'Usuario')], default='usuario', max_length=20),
        ),
    ]
