# Generated by Django 5.2 on 2025-05-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresia',
            name='fecha_fin',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='membresia',
            name='fecha_inicio',
            field=models.DateField(editable=False),
        ),
    ]
