# Generated by Django 5.2 on 2025-05-27 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0003_alter_membresia_fecha_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='membresia_activa',
        ),
    ]
